server:
  port: 10000

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/today_diary
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.diary.today.entity